export const searchData = {
  songs: [
    {
      id: 1,
      title: "Solana Sunrise",
      artist: "CryptoBeats",
      image: "/abstract-music-visualizer-purple.png",
      duration: "3:24",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      plays: 245,
      genre: "Electronic",
      isVerified: true,
      type: "Song",
    },
    {
      id: 2,
      title: "Digital Dreams",
      artist: "Virtual Vibes",
      image: "/abstract-music-visualizer-blue.png",
      duration: "4:12",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      plays: 187,
      genre: "Ambient",
      isVerified: true,
      type: "Song",
    },
    {
      id: 3,
      title: "Metaverse Melody",
      artist: "Blockchain Beats",
      image: "/abstract-music-visualizer-pink.png",
      duration: "2:57",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
      plays: 132,
      genre: "Chillwave",
      isVerified: true,
      type: "Song",
    },
    {
      id: 4,
      title: "Crypto Beats",
      artist: "BlockchainDJ",
      image: "/electronic-purple-album-cover.png",
      duration: "3:45",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
      plays: 543,
      genre: "Electronic",
      isVerified: true,
      type: "Song",
    },
    {
      id: 5,
      title: "NFT Nights",
      artist: "TokenTunes",
      image: "/night-city-neon-album-cover.png",
      duration: "5:20",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
      plays: 321,
      genre: "Lo-Fi",
      isVerified: false,
      type: "Song",
    },
    {
      id: 6,
      title: "Blockchain Blues",
      artist: "Crypto Cat",
      image: "/moody-blue-album-art.png",
      duration: "5:12",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
      plays: 432,
      genre: "Blues",
      isVerified: false,
      type: "Song",
    },
    {
      id: 7,
      title: "Metaverse Melodies",
      artist: "Virtual Vibes",
      image: "/futuristic-colorful-album-cover.png",
      duration: "4:20",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      plays: 765,
      genre: "Ambient",
      isVerified: true,
      type: "Song",
    },
    {
      id: 8,
      title: "Decentralized Dreams",
      artist: "Web3 Wizard",
      image: "/abstract-digital-dream-album-cover.png",
      duration: "6:15",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
      plays: 289,
      genre: "Experimental",
      isVerified: false,
      type: "Song",
    },
  ],
  artists: [
    {
      id: "artist-1",
      name: "CryptoBeats",
      image: "/placeholder.svg?height=400&width=400&query=dj+profile+purple+neon",
      trackCount: 12,
      type: "Artist",
    },
    {
      id: "artist-2",
      name: "Virtual Vibes",
      image: "/placeholder.svg?height=400&width=400&query=electronic+artist+profile+blue",
      trackCount: 8,
      type: "Artist",
    },
    {
      id: "artist-3",
      name: "Blockchain Beats",
      image: "/placeholder.svg?height=400&width=400&query=music+producer+profile+dark",
      trackCount: 15,
      type: "Artist",
    },
    {
      id: "artist-4",
      name: "TokenTunes",
      image: "/placeholder.svg?height=400&width=400&query=dj+profile+colorful",
      trackCount: 6,
      type: "Artist",
    },
    {
      id: "artist-5",
      name: "Web3 Wizard",
      image: "/placeholder.svg?height=400&width=400&query=electronic+artist+profile+mystical",
      trackCount: 9,
      type: "Artist",
    },
    {
      id: "artist-6",
      name: "Crypto Cat",
      image: "/placeholder.svg?height=400&width=400&query=female+dj+profile+neon",
      trackCount: 7,
      type: "Artist",
    },
  ],
  albums: [
    {
      id: 101,
      title: "Blockchain Beats Vol. 1",
      artist: "CryptoBeats",
      image: "/electronic-purple-album-cover.png",
      trackCount: 10,
      releaseDate: "2023-05-15",
      type: "Album",
    },
    {
      id: 102,
      title: "Digital Dreamscape",
      artist: "Virtual Vibes",
      image: "/abstract-music-visualizer-blue.png",
      trackCount: 8,
      releaseDate: "2023-06-22",
      type: "Album",
    },
    {
      id: 103,
      title: "Metaverse Melodies",
      artist: "Blockchain Beats",
      image: "/futuristic-colorful-album-cover.png",
      trackCount: 12,
      releaseDate: "2023-04-10",
      type: "Album",
    },
    {
      id: 104,
      title: "NFT Nights",
      artist: "TokenTunes",
      image: "/night-city-neon-album-cover.png",
      trackCount: 9,
      releaseDate: "2023-07-05",
      type: "Album",
    },
    {
      id: 105,
      title: "Decentralized Dreams",
      artist: "Web3 Wizard",
      image: "/abstract-digital-dream-album-cover.png",
      trackCount: 7,
      releaseDate: "2023-03-18",
      type: "Album",
    },
  ],
  playlists: [
    {
      id: "playlist-1",
      title: "Crypto Chill",
      description: "Relaxing blockchain beats for your coding sessions",
      image: "/placeholder.svg?height=400&width=400&query=chill+music+visualization+purple",
      trackCount: 25,
      curator: "SubTerrain",
      type: "Playlist",
    },
    {
      id: "playlist-2",
      title: "NFT Dance Party",
      description: "High energy tracks for your next metaverse event",
      image: "/placeholder.svg?height=400&width=400&query=dance+music+visualization+colorful",
      trackCount: 18,
      curator: "CryptoBeats",
      type: "Playlist",
    },
    {
      id: "playlist-3",
      title: "Blockchain Ambient",
      description: "Atmospheric sounds from the decentralized music scene",
      image: "/ambient-blue-visualization.png",
      trackCount: 32,
      curator: "Virtual Vibes",
      type: "Playlist",
    },
    {
      id: "playlist-4",
      title: "Web3 Workout",
      description: "Energetic tracks to power your exercise routine",
      image: "/placeholder.svg?height=400&width=400&query=workout+music+visualization+energetic",
      trackCount: 15,
      curator: "TokenTunes",
      type: "Playlist",
    },
    {
      id: "playlist-5",
      title: "Crypto Focus",
      description: "Concentration-enhancing tracks for deep work",
      image: "/placeholder.svg?height=400&width=400&query=focus+music+visualization+minimal",
      trackCount: 40,
      curator: "SubTerrain",
      type: "Playlist",
    },
  ],
  nfts: [
    {
      id: "nft-1",
      title: "Digital Symphony #42",
      artist: "CryptoBeats",
      image: "/placeholder.svg?height=400&width=400&query=digital+music+nft+purple",
      price: "0.5 SOL",
      type: "NFT",
    },
    {
      id: "nft-2",
      title: "Virtual Soundscape #7",
      artist: "Virtual Vibes",
      image: "/placeholder.svg?height=400&width=400&query=virtual+music+nft+blue",
      price: "0.8 SOL",
      type: "NFT",
    },
    {
      id: "nft-3",
      title: "Blockchain Beats Original",
      artist: "Blockchain Beats",
      image: "/placeholder.svg?height=400&width=400&query=blockchain+music+nft+colorful",
      price: "1.2 SOL",
      type: "NFT",
    },
    {
      id: "nft-4",
      title: "Token Tune #15",
      artist: "TokenTunes",
      image: "/placeholder.svg?height=400&width=400&query=token+music+nft+neon",
      price: "0.6 SOL",
      type: "NFT",
    },
    {
      id: "nft-5",
      title: "Web3 Wizard's Spell",
      artist: "Web3 Wizard",
      image: "/placeholder.svg?height=400&width=400&query=wizard+music+nft+mystical",
      price: "2.0 SOL",
      type: "NFT",
    },
    {
      id: "nft-6",
      title: "Crypto Cat's Purr",
      artist: "Crypto Cat",
      image: "/placeholder.svg?height=400&width=400&query=cat+music+nft+cute",
      price: "0.4 SOL",
      type: "NFT",
    },
  ],
}
